export type Language = 'common'
  | 'dwarvish'
  | 'elvish'
  | 'giant'
  | 'gnomish'
  | 'goblin'
  | 'halfling'
  | 'orc'
  | 'abyssal'
  | 'celestial'
  | 'draconic'
  | 'deep speech'
  | 'infernal'
  | 'primordial'
  | 'sylvan'
  | 'undercommon';
